version: "3"
services:
        db:
                image: postgres:12.0-alpine
                environment:
                        - POSTGRES_PASSWORD=secret
                        - POSTGRES_USER=press
                        - POSTGRES_DB=wordpress
                volumes:
                        - ./data/:/var/lib/postgresql/data/
                ports:
                        - 5431:5432

        wordpress:
                image: wordpress:v2
                ports:
                        - 80:80
                links:
                        - db:database
                environment:
                        - WORDPRESS_DB_HOST=database:5431
                        - WORDPRESS_DB_USER=press
                        - WORDPRESS_DB_PASSWORD=secret
                        - WORDPRESS_DB_NAME=wordpress
                          #volumes:
                          #- ./html/:/var/www/html
